steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', 't', 'gcr.io/capstone-deploy-447802/chatbot-app:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/capstone-deploy-447802/chatbot-app:latest']
     
images:
  - 'gcr.io/capstone-deploy-447802/chatbot-app:latest'