options:
  logging: CLOUD_LOGGING_ONLY
steps:
  #build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/capstone-deploy-447802/chatbot-app:latest', '.']
  #push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/capstone-deploy-447802/chatbot-app:latest']
  #deploy to cloud run
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: gcloud
  #   args: ['run', 'deploy', 'chatbot-app', '--image', 'gcr.io/capstone-deploy-447802/chatbot-app:latest', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
  
  # auth
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials ci-cd-capstone-cluster --zone asia-east2 --project capstone-deploy-447802

  #deploy to gke
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
        kubectl apply -f kubernetes/app-secrets.yaml
        kubectl apply -f kubernetes/my-pod.yaml
        kubectl set image deployment/tes-capstone tes-capstone=gcr.io/capstone-deploy-447802/chatbot-app:latest
images:
  - 'gcr.io/capstone-deploy-447802/chatbot-app:latest'