apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: api-provider
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/capstone-deploy-447802/secrets/OPENAI_API_KEY/versions/1"
        path: "D:\RL\IYKRA\Capstone\OPENAI_API_KEY.txt"
      - resourceName: "projects/capstone-deploy-447802/secrets/REPLICATE_API_TOKEN/versions/1"
        path: "D:\RL\IYKRA\Capstone\REPLICATE_API_TOKEN.txt"
        