apiVersion: v1
kind: Pod
metadata:
  name: tes-capstone-5d454cc7f8-pxwkp
  namespace: secret-manager-access
spec:
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"
  serviceAccountName: secret-manager-service
  containers:
  - image: gcr.io/capstone-deploy-447802/chatbot-app:latest
    imagePullPolicy: IfNotPresent
    name: tes-capstone-5d454cc7f8-pxwkp
    resources:
      requests:
        cpu: 100m
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
      - mountPath: "/var/secrets"
        name: mysecret
  volumes:
  - name: mysecret
    csi:
      driver: secrets-store-gke.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: api_provider
        