apiVersion: v1
kind: Pod
metadata:
  name: tes-capstone
  namespace: secret-manager-access
spec:
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"
  serviceAccountName: secret-manager-service
  containers:
  - image: gcr.io/capstone-deploy-447802/chatbot-app:latest
    imagePullPolicy: Always
    name: tes-capstone
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
      - mountPath: "/var/secrets"
        name: mysecret
    env:
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: my-apis
          key: OPENAI_API_KEY
    - name: REPLICATE_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: my-apis
          key: REPLICATE_API_TOKEN
  volumes:
  - name: mysecret
    csi:
      driver: secrets-store-gke.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: api_provider
